"""initial_schema"""
from alembic import op
import sqlalchemy as sa
revision = 'b2dd4b2ded65'
down_revision = None
branch_labels = None
depends_on = None

def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('login_attempts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(length=64), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_login_attempts_created'), 'login_attempts', ['created'], unique=False)
    op.create_index(op.f('ix_login_attempts_key'), 'login_attempts', ['key'], unique=False)
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=254), nullable=False),
    sa.Column('name', sa.String(length=120), nullable=False),
    sa.Column('password_hash', sa.Text(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('active', sa.Boolean(), nullable=False),
    sa.Column('wiw_user_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('wiw_user_id')
    )
    op.create_table('changes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.Column('wiw_user_id', sa.Integer(), nullable=False),
    sa.Column('action', sa.String(length=20), nullable=False),
    sa.Column('event_id', sa.Integer(), nullable=True),
    sa.Column('proposed', sa.JSON(), nullable=False),
    sa.Column('before', sa.JSON(), nullable=False),
    sa.Column('read_start', sa.String(length=60), nullable=False),
    sa.Column('read_end', sa.String(length=60), nullable=False),
    sa.Column('status', sa.String(length=40), nullable=False),
    sa.Column('employee_note', sa.Text(), nullable=False),
    sa.Column('manager_note', sa.Text(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=True),
    sa.Column('dry_run', sa.Boolean(), nullable=True),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_changes_employee_id'), 'changes', ['employee_id'], unique=False)
    op.create_index(op.f('ix_changes_status'), 'changes', ['status'], unique=False)
    op.create_table('manager_scopes',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('manager_id', sa.Integer(), nullable=False),
    sa.Column('location', sa.String(length=120), nullable=False),
    sa.ForeignKeyConstraint(['manager_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('manager_id', 'location')
    )
    op.create_table('sessions',
    sa.Column('digest', sa.String(length=64), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('expires', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('digest')
    )
    op.create_index(op.f('ix_sessions_user_id'), 'sessions', ['user_id'], unique=False)
    op.create_table('audit',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('change_id', sa.Integer(), nullable=False),
    sa.Column('actor_id', sa.Integer(), nullable=True),
    sa.Column('event', sa.String(length=60), nullable=False),
    sa.Column('details', sa.JSON(), nullable=False),
    sa.Column('created', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['change_id'], ['changes.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_change_id'), 'audit', ['change_id'], unique=False)
    # ### end Alembic commands ###

def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_audit_change_id'), table_name='audit')
    op.drop_table('audit')
    op.drop_index(op.f('ix_sessions_user_id'), table_name='sessions')
    op.drop_table('sessions')
    op.drop_table('manager_scopes')
    op.drop_index(op.f('ix_changes_status'), table_name='changes')
    op.drop_index(op.f('ix_changes_employee_id'), table_name='changes')
    op.drop_table('changes')
    op.drop_table('users')
    op.drop_index(op.f('ix_login_attempts_key'), table_name='login_attempts')
    op.drop_index(op.f('ix_login_attempts_created'), table_name='login_attempts')
    op.drop_table('login_attempts')
    # ### end Alembic commands ###
